### ISSUE TITLE
El ejercicio de ciclar no está usando el test adecuado

### ISSUE THREAD

**Issue by mmatos** [pdep-utn/mumuki-guia-practica-evaluacion-diferida#1]
Al resolver http://mumuki.io/exercises/1800-programacion-funcional-practica-evaluacion-diferida-ciclar tira este error

/tmp/compilation58:12:4:
    Couldn't match expected type ‘[t0] -> [t1]’ with actual type ‘[a0]’
    The function ‘take’ is applied to three arguments,
    but its type ‘Int -> [a0] -> [a0]’ has only two
    In the first argument of ‘shouldBe’, namely ‘take 6 ciclar [0, 1]’
    In a stmt of a 'do' block:
      take 6 ciclar [0, 1] `shouldBe` [0, 1, 0, 1, ....](deferred type error)

Sin embargo eso ya está arreglado en el test del ejercicio ciclar (en el repo aparece como  take 6 (ciclar [0, 1]) así que no parece ser un problema del editor)

**Comment by mmatos** [comment]
El problema es que la guía está duplicada y la que está publicada no es la misma que puede ser editada. Una vez arreglado el linkeo y borrada la guía incorrecta debería solucionarse.

**Comment by flbulgarelli** [comment]
Resuelto
